### ISSUE TITLE
No Sleep Data 

### ISSUE THREAD

**Issue by muhammadabbas001** [tryVital/vital-ios#98]
I am trying to fetch sleep data using Apple Health Kit and Vital but no sleep data coming.

```Swift

guard let provider = self.vitalSleepProvider else {
     throw "No Sleep Provider Selected"
}
            
if let data = try await VitalHealthKitClient.read(resource: .sleep, startDate: Date.now.addingTimeInterval(.days(-30)), endDate: Date.now){
     print(data)
}

```

<img width="363" alt="Screenshot 2023-11-28 at 2 13 31 AM" src="https://github.com/tryVital/vital-ios/assets/73989872/ddcef694-3e1c-421b-b93e-bd41c555e5e5">

- Why there is no data for sleep summary?
- I have added some sleep data to the Apple Health App but no data is coming here
- What could be the problem with this?
- If I fetch sleep data directly using HealthKit then getting some data successfully

**Comment by RuiAAPeres** [comment]
Hi 👋 did you ask permissions to access sleep data?

**Comment by muhammadabbas001** [comment]
No, I have successfully configured the permissions but sleep data is not coming.

**Comment by muhammadabbas001** [comment]
Remember I have put the sleep data manually into the Apple Health App

**Comment by RuiAAPeres** [comment]
Can you show me how you configured the permissions?

**Comment by muhammadabbas001** [comment]
@RuiAAPeres  The manualy entered data is not coming with this SDK. I have checked that with my other apple id where I have one dynamic entery of sleep data and that entry successfully fetched by this SDK. What could be the issue?

**Comment by RuiAAPeres** [comment]
@muhammadabbas001 I got a message from my colleague @andersio on this matter. We are filtering sleeps. Here: https://github.com/tryVital/vital-ios/blob/6acd8a050fd6f980d0e3ebcfaf101560d1d8131b/Sources/VitalHealthKit/HealthKit/HealthKitReads.swift#L452

**Comment by muhammadabbas001** [comment]
Can we remove that or update that?

**Comment by RuiAAPeres** [comment]
Not in the short term. We can add a flag when configuring the SDK to allow any sleeps to come in tho.

**Comment by muhammadabbas001** [comment]
Ok, thanks for that kind cooperation.

**Comment by RuiAAPeres** [comment]
I am closing this issue for now @muhammadabbas001. When we add the flag, I will ping you. Thank you.
